# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: babffab4f354fa7d74ac8c844bea0caf9c60d0fe951e0ea81ad5fe288e992fc44127b0a21c5129ec1a37d9f91e0f176ae30d0924ed707443ddea9bef7b13945d

test:
  secret_key_base: cb9783982138dd553f5b63532aaa1eaf49564cd283ecc8ff226f5b0fccfd0e6cf9a8f0485eca3c26d4776e4c1a9c489d327e0ae7c54f2b7a4eaa33f0e82e8446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
