# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf4412dcfe8d3ea2dc2bf840f03ffef4763e6a75c6a21207e420fd9bc2d25640f4f28f3fc0ed6c38dd42a2e20d49cab6e83fce7225a944c19777f996e76fe17

test:
  secret_key_base: 3e50f87aa0cb01038d5a27a351f3e393121866ddc557a12a6ec0abf856542e75b8d78fb3eee10a64502cf2091028449061aad51e59bd0cfad66f4c445e012b98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
